### ISSUE TITLE
Build fail with onnxruntime 1.13 (git)

### ISSUE THREAD

**Issue by blackPantherOS** [royshil/obs-backgroundremoval#118]
Hi, I got this error with git version of onnxruntime (1.13.0)

```
obs-backgroundremoval/src/background-filter.cpp
/usr/src/RPM/BUILD/obs-backgroundremoval/src/background-filter.cpp:6:2: error: #endif without #if
    6 | #endif
      |  ^~~~~
In file included from /usr/src/RPM/BUILD/obs-backgroundremoval/src/background-filter.cpp:25:
/usr/src/RPM/BUILD/obs-backgroundremoval/src/Model.h: In member function ‘virtual void Model::populateInputOutputNames(const std::unique_ptr<Ort::Session>&, std::vector<const char*>&, std::vector<const char*>&)’:
/usr/src/RPM/BUILD/obs-backgroundremoval/src/Model.h:88:41: error: ‘struct Ort::Session’ has no member named ‘GetInputName’
   88 |           inputNames.push_back(session->GetInputName(0, allocator));
      |                                         ^~~~~~~~~~~~
/usr/src/RPM/BUILD/obs-backgroundremoval/src/Model.h:89:40: error: ‘struct Ort::Session’ has no member named ‘GetOutputName’
   89 |         outputNames.push_back(session->GetOutputName(0, allocator));
      |                                        ^~~~~~~~~~~~~
/usr/src/RPM/BUILD/obs-backgroundremoval/src/Model.h: In member function ‘virtual void ModelRVM::populateInputOutputNames(const std::unique_ptr<Ort::Session>&, std::vector<const char*>&, std::vector<const char*>&)’:
/usr/src/RPM/BUILD/obs-backgroundremoval/src/Model.h:375:41: error: ‘struct Ort::Session’ has no member named ‘GetInputName’
  375 |           inputNames.push_back(session->GetInputName(i, allocator));
      |                                         ^~~~~~~~~~~~
/usr/src/RPM/BUILD/obs-backgroundremoval/src/Model.h:378:42: error: ‘struct Ort::Session’ has no member named ‘GetOutputName’
  378 |           outputNames.push_back(session->GetOutputName(i, allocator));
      |                                          ^~~~~~~~~~~~~
/usr/src/RPM/BUILD/obs-backgroundremoval/src/background-filter.cpp: In function ‘void createOrtSession(background_removal_filter*)’:
/usr/src/RPM/BUILD/obs-backgroundremoval/src/background-filter.cpp:211:31: error: ‘OrtSessionOptionsAppendExecutionProvider_DML’ was not declared in this scope; did you mean ‘OrtSessionOptionsAppendExecutionProvider_CPU’?
  211 |             Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_DML(sessionOptions, 0));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               OrtSessionOptionsAppendExecutionProvider_CPU

```

The build succesful with onnxruntime.1.12 

```
make[2]: Leaving directory '/usr/src/RPM/BUILD/obs-backgroundremoval/build'
[100%] Built target obs-backgroundremoval
make[1]: Leaving directory '/usr/src/RPM/BUILD/obs-backgroundremoval/build'
/usr/bin/cmake -E cmake_progress_start /usr/src/RPM/BUILD/obs-backgroundremoval/build/CMakeFiles 0

```

**Comment by HTLife** [comment]
This is the git diff to fix the `Model.h` build error when upgrade to 1.13.1
[Model.h_diff.txt](https://github.com/royshil/obs-backgroundremoval/files/10317322/Model.h_diff.txt)

**Comment by royshil** [comment]
this should be resolved now on main HEAD

**Comment by royshil** [comment]
this is resolved
